poetry.lock
pyproject.toml
release_tools/publish.py
release_tools/semverup.py
releases/unreleased/update-version-in-pyproject-file.yml
tests/test_publish.py
tests/test_semverup.py

Besides the file `_version.py`, there is another file that stores the version number of the package. This file is `pyproject.toml` and is used by `poetry` to generate Python packages and source code tarballs.
With this PR `semverup` will also update this version number when called. Command `publish` will include the file within the release commit.
To test it, run `semverup` with some unreleased changes. You'll see both `_version.py` and `pyproject.toml` files have changed. Then, generate the release notes with `notes` and generate the release commit and tag calling `publish`. This command will commit the changes in `pyproject.toml`.

Automate version updates in pyproject file

---

release_tools/notes.py
release_tools/project.py
release_tools/publish.py
releases/unreleased/update-news-file-with-the-latest-relase-notes.yml
tests/test_notes.py
tests/test_project.py
tests/test_publish.py

This PR allows to update the NEWS file when new release notes are produced. To update it, use the parameter `--news` while running `notes` command.

Update news file

---

release_tools/publish.py
releases/unreleased/push-release-only-with-only-push.yml
tests/test_publish.py

The command `publish` generates the commit and tag release but by default it does not push them to a remote repository. The idea behind this is to review the changes before pushing them. After the review, to upload the new changes, it will necessary to call directly to `git push` because `publish` will try to create the same release data again.
To fix this problem a the new flag `--only-push` is available. When it is called together with `--push`, the command will ignore the creation of the release pushing to the origin the latest changes.
Signed-off-by: Santiago Dueñas <sduenas@bitergia.com>

[publish] Allow to push only the release commit

---

README.md

This commits adds some documentation to the README file. It includes a generic description about how to use the tools and how to install the package.
It addresses the issue #11.

Add documentation about usage and contents

---

README.md
release_tools/changelog.py
release_tools/entry.py
release_tools/notes.py
releases/unreleased/push-release-only-with-only-push.yml
releases/unreleased/replace-pull-request-field-for-issue-in-changelog-entries.yml
releases/unreleased/update-news-file-with-the-latest-relase-notes.yml
releases/unreleased/update-version-in-pyproject-file.yml
tests/test_changelog.py
tests/test_entry.py
tests/test_notes.py
tests/test_semverup.py

This PR updates the structure of the changelog entry. So far, it included the field `pull_request` but we considered `issue` is more generic and more useful.
This PR fixes #10.

Replace pr for issue field

---

release_tools/publish.py
releases/unreleased/check-if-unreleased-dir-exists-when-publishing.yml
tests/test_publish.py

An exception was raised when `publish` command was called and `unreleased` directory did not exist. Now, instead of raising an exception, `publish` command fails and displays a message with the error.
This PR fixes the error reported in #5.

Fix error in publish when unreleased directory does not exist

---

release_tools/publish.py
release_tools/repo.py
releases/unreleased/recover-from-the-inconsistent-stage-after-publish-fails.yml
tests/test_publish.py

If publish fails, the command leaves the git repository in an inconsistent state. This PR informs about the possible errors and adds the support of rollback to the last consistent state. This is needed to save the manual effort of the user to fix the status of the repository. Tests are added accordingly.
Fixes #18.

[publish] Recover from the inconsistent state

---

tests/test_changelog.py
tests/test_notes.py
tests/test_semverup.py

A few tests are failing when you install release-tools as a package. This PR fixes all those failing tests.
This is necessary as we would soon upload automate the release process using github actions and upload the package to PyPI whenever there is a new release.
It also fixes a few flake8 errors.

[tests] Fix failing tests

---

.github/workflows/tests.yml
README.md

This PR replaces the coveralls service with codecov in the tests workflow as there are a lot of problems with coveralls lately.
Closes #26

[tests] Replace coveralls with codecov

---

.github/workflows/release.yml

This commit updates the installation method of poetry in the release workflow as it is advised to use the latest version of poetry.

[release] Update poetry installation

---

.github/workflows/tests.yml

The codecov gives a warning if the depth is not set accordingly during actions/checkout.
```
->  Issue detecting commit SHA. Please run actions/checkout with fetch-depth > 1 or set to 0
```
This PR is required to override this error.

[tests] Set the fetch-depth to 10

---

README.md
release_tools/notes.py
release_tools/project.py
release_tools/publish.py
releases/unreleased/add-option-to-update-authors-file-content.yml
tests/test_notes.py
tests/test_project.py
tests/test_publish.py

This PR adds the option '--authors' which allows updating the authors file with the contributors' names.
The tests are added and the documentation is updated accordingly.

[notes] Add option to update authors file content

---

.github/workflows/changelog.yml

This pull request adds a new GitHub workflow to check if a changelog file was included in the last pull request and validate the contents if it is empty or valid YAML file.
It can be used from a different repository using
```
name: Changelog included
on:
pull_request:
branches:
- master
jobs:
check-changelog:
uses: bitergia/release-tools/.github/workflows/changelog.yml@master
```

[gha] Reusable workflow to check if a changelog was included

---

release_tools/entry.py
releases/unreleased/changelog-valid-filenames.yml
tests/test_entry.py

This commit updates how `changelog` creates the file name and ignores any characters other than alphanumeric, `_` or `-` to avoid errors when using `/`, `'` or `"`, among others, in titles.

Improve file name for changelog

---

release_tools/publish.py
release_tools/semverup.py
releases/unreleased/option-for-release-candidates-versions.yml
releases/unreleased/publish-unreleased-files-management.yml
tests/test_publish.py
tests/test_semverup.py

Include a new option in the `publish` command (`--no-cleanup`) for not removing changelog entries when a new release is generated.
Include a new option in the `semverup` command (`--prerelease`) to create a new release candidate based on the notes or the changelog entries. Some cases for the `semverup` command:
Initial version: `0.2.0`:
- No changelog `semverup --prerelease`: `error`
- Changelog minor `semverup --prerelease`: `0.3.0-rc.1`
- `semverup --bump-version=PATCH --prerelease`: `0.2.1-rc.1`
Initial version:  `0.2.1-rc.1`:
- No changelog `semverup`: `error`
- No changelog `semverup --prerelease`: `error`
- With changelog `semverup`: `0.2.1`
- With changelog `semverup --prerelease`: `0.2.1-rc.2`
- `semverup --bump-version=PATCH`: `0.2.1`
- `semverup --bump-version=PATCH …

Options to create release candidates

---

.github/workflows/release.yml
.github/workflows/tests.yml

This PR updates the way the release is generated. actions/create-release is deprecated, and now the command `gh release create` is the best way of creating a new release from a GitHub workflow.
This PR also updates the version number of the actions being used. Now they will use the commit SHA of a released action 
version because it is the best for stability and security.

[actions] Update release workflow and include SHA version in each action

---

README.md
release_tools/changelog.py
release_tools/entry.py
release_tools/semverup.py
releases/unreleased/categories-bumps-version-changed.yml
tests/test_changelog.py
tests/test_entry.py
tests/test_semverup.py

This PR includes a new Category for updates on dependencies. This is needed when a new version is required when dependencies are updated. It will increase the `patch` version.
Previously, only the 'fixed' notes incremented the 'patch' version, and the other changes incremented MINOR. We updated this behavior.
From now on, 'changed' and 'removed' entries increment major version. 'Added', 'deprecated', 'security', 'performance' and
'other' increment the minor version. 'Fixed' and 'dependency' increment the patch version.
Closes https://github.com/Bitergia/release-tools/issues/55

Update what version increments each category and add 'dependecy' category

---

README.md
release_tools/notes.py
release_tools/project.py
release_tools/publish.py
release_tools/repo.py
releases/unreleased/changelog-location-updated-between-versions.yml
tests/test_notes.py
tests/test_project.py
tests/test_publish.py
tests/test_repo.py

`notes` move the changelog entries to a new directory when they are used for creating a release notes file. `Notes` has a now a new argument `--pre-release`, when it is defined, it ignores `unreleased/processed` notes for creating new release notes, when it is not passed, it includes 'unreleased/processed' in release notes.
`semverup` now updates the version depending on the notes that are in `unreleased` directory and ignores `unreleased/processed`.
`publish` removes the notes at unreleased/processed because are the notes that are already processed and ignores the yml files at `unreleased/*.yml`

[notes] Move notes to a new directory for every version

---

release_tools/semverup.py
releases/unreleased/next-version-on-semverup-fixed.yml
tests/test_semverup.py

`semverup` was not increasing the correct version number when the old version was a release candidate and a new changelog was included. 
It was increasing only the release candidate number. Now it increases correctly the number based on new changelog entries.
Tests are added for almost any case.

[semverup] Next version on semverup fixed

---

release_tools/publish.py
releases/unreleased/option-to-include-branch-in-publish.yml
tests/test_publish.py

Include the `--remote-branch <branch>` option in `publish` to push to a specific remote branch. By default it is `master`.

[publish] Option to push to a specific branch

---

.github/workflows/release.yml

This PR replaces a typo in the workflow that was using input instead of secrets.

Fix release workflow including token

---

.github/workflows/tests.yml
README.md
poetry.lock
pyproject.toml

Update GitHub actions to use coveralls instead of Codecov.

Migrate from Codecov to Coveralls

---

.github/workflows/changelog.yml
README.md

Update files to support the migration of GrimoireLab repositories as part of the default branch transition from master to main.

Migrate files for branch rename from master to main
